mysql:
  dsn: "cp_65011212040:65011212040@csmsu@tcp(202.28.34.197:3306)/cp_65011212040?collation=utf8mb4_unicode_ci&parseTime=true"
# user:pwd@tcp(ip:port)/dbname?collation=utf8mb4_unicode_ci&parseTime=true